### ISSUE TITLE
Question on same-origin policy (SOP) across iframes

### ISSUE THREAD

**Issue by bitsofparag** [PAM-AS/PAMWebBrowser#7]
Does `PAMWebBrowser`'s webkit implementation allow access to web preferences so that one can disable SOP across iframes that have different origins? Or is it just a view controller built over the standard iOS Webkit library?

**Comment by thomassnielsen** [comment]
PAMWebBrowser is just a wrapper around UIWebView with a navigation system, and as such shares all the same traits and APIs as UIWebView.
